spring:
  application:
    name: taskmanagementsystem
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanagement
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # MOVE THIS INSIDE 'spring'
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
